##模板内参数信息(一般不需要修改)---------
batch_size = 4     #name=批处理大小     #description=每批读入数据数量
model_name = 'hrnet'     #name=模型名称     #description=
val_interval = 100     #name=验证周期     #description=验证周期
max_iters = 3200     #name=最大训练周期     #description=模型训练最大周期
retrain_pth_url = '/mnt/cangling/ib/data/train/detect/mmsegmentation/pth/best_mIoU_iter_1200.pth'     #name=重训练文件路径     #description=重训练参数文件路径
crop_size = (1024,1024)     #name=图像大小     #description=训练图像大小
env = 'mmsegmentation'     #name=系统参数     #description=系统参数
checkpoint_path = '/mnt/cangling/ib/data/train/detect/mmsegmentation/pth'     #name=系统参数     #description=系统参数
log_path = '/mnt/cangling/ib/data/train/detect/mmsegmentation/log'     #name=系统参数     #description=系统参数
tensorboard_log_path = '/data/train/tensorboard/train-2c'     #name=系统参数     #description=系统参数
work_space = '/mnt/cangling/ib/data/train/detect/mmsegmentation'     #name=系统参数     #description=系统参数
use_tensorboard_scalar = True     #name=系统参数     #description=系统参数
use_tensorboard_image = True     #name=系统参数     #description=系统参数
work_dir = '/mnt/cangling/ib/data/train/detect/mmsegmentation'     #name=系统参数     #description=系统参数
pretrained = '/mnt/cangling/ib/data/train/common_pth'     #name=系统参数     #description=系统参数
use_filelist = True     #name=系统参数     #description=系统参数
train_img_list = '/mnt/cangling/ib/data/train/detect/mmsegmentation/config/train_img_list.txt'     #name=系统参数     #description=系统参数
train_gt_list = '/mnt/cangling/ib/data/train/detect/mmsegmentation/config/train_gt_list.txt'     #name=系统参数     #description=系统参数
val_img_list = '/mnt/cangling/ib/data/train/detect/mmsegmentation/config/val_img_list.txt'     #name=系统参数     #description=系统参数
val_gt_list = '/mnt/cangling/ib/data/train/detect/mmsegmentation/config/val_gt_list.txt'     #name=系统参数     #description=系统参数
train_img_suffix = '.tif'     #name=系统参数     #description=系统参数
train_gt_suffix = '.tif'     #name=系统参数     #description=系统参数
val_img_suffix = '.tif'     #name=系统参数     #description=系统参数
val_gt_suffix = '.tif'     #name=系统参数     #description=系统参数
mean_file = '/mnt/cangling/ib/data/train/detect/mmsegmentation/config/mean_value.txt'     #name=系统参数     #description=系统参数
std_file = '/mnt/cangling/ib/data/train/detect/mmsegmentation/config/std_value.txt'     #name=系统参数     #description=系统参数
num_classes = 2     #name=系统参数     #description=系统参数
classes_name = ('无效值','水体')     #name=系统参数     #description=系统参数
palette = [[0,0,0],[48,169,206]]     #name=系统参数     #description=系统参数
gpu_num = 1     #name=系统参数     #description=系统参数
# img_list_file = '/mnt/cangling/ib/data/train/detect/mmsegmentation/config/val_img_list.txt'    #name=待挖掘影像列表    #description=存放需要被推理和生成SHP的无标注TIF影像路径TXT
# output_root = '/mnt/cangling/ib/data/train/detect/mmsegmentation/mining_output'
resume_mode = 'None'

