##模板内参数信息(一般不需要修改)---------
env = 'yc-cc384c-8ad'     #name=系统参数     #description=系统参数
checkpoint_path = '/data/train/model/train-32/pth'     #name=系统参数     #description=系统参数
log_path = '/data/train/model/train-32/log'     #name=系统参数     #description=系统参数
tensorboard_log_path = '/data/train/tensorboard/train-32'     #name=系统参数     #description=系统参数
work_space = '/data/train/model/train-32'     #name=系统参数     #description=系统参数
use_tensorboard_scalar = True     #name=系统参数     #description=系统参数
use_tensorboard_image = True     #name=系统参数     #description=系统参数
work_dir = '/data/train/model/train-32'     #name=系统参数     #description=系统参数
pretrained = '/data/train/common_pth'     #name=系统参数     #description=系统参数
data_file = '/data/train/model/train-32/config/data.yaml'     #name=系统参数     #description=系统参数
gpu_num = 1     #name=系统参数     #description=系统参数
img_list_file = '/data/train/predict/yc-cc384c-8ad/config/img_list.txt'     #name=系统参数     #description=系统参数
color_table_file = '/data/train/predict/yc-cc384c-8ad/config/color_table.txt'     #name=系统参数     #description=系统参数
num_classes = 20     #name=系统参数     #description=系统参数
load_model_path = '/data/train/model/train-32/pth/best.pt'     #name=系统参数     #description=系统参数
output_root = '/share/ib/3/288/output/predict/飞机识别yolo26'     #name=系统参数     #description=系统参数
bootstrap_servers = '192.168.1.166:12007'     #name=系统参数     #description=系统参数
topic = 'ib-theme.algorithm_callback_topic'     #name=系统参数     #description=系统参数
projectId = 288     #name=系统参数     #description=系统参数
taskId = 5224     #name=系统参数     #description=系统参数
use_color_out = True     #name=系统参数     #description=系统参数
use_shapefile_out = True     #name=系统参数     #description=系统参数
